package com.hqw.voteme.mapper;

import com.hqw.voteme.domain.CProvince;

public interface CProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_province
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_province
     *
     * @mbggenerated
     */
    int insert(CProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_province
     *
     * @mbggenerated
     */
    int insertSelective(CProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_province
     *
     * @mbggenerated
     */
    CProvince selectByPrimaryKey(Integer provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CProvince record);
}