package com.hqw.voteme.mapper;

import com.hqw.voteme.domain.UserProfile;

public interface UserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userProfileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int insert(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int insertSelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    UserProfile selectByPrimaryKey(Integer userProfileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_profile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserProfile record);
}