package com.hqw.voteme.mapper;

import com.hqw.voteme.domain.VillageManager;

public interface VillageManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village_manager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer villageManagerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village_manager
     *
     * @mbggenerated
     */
    int insert(VillageManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village_manager
     *
     * @mbggenerated
     */
    int insertSelective(VillageManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village_manager
     *
     * @mbggenerated
     */
    VillageManager selectByPrimaryKey(Integer villageManagerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VillageManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table village_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VillageManager record);
}