package com.hqw.voteme.mapper;

import com.hqw.voteme.domain.VoteOptions;

public interface VoteOptionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_options
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_options
     *
     * @mbggenerated
     */
    int insert(VoteOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_options
     *
     * @mbggenerated
     */
    int insertSelective(VoteOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_options
     *
     * @mbggenerated
     */
    VoteOptions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_options
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VoteOptions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_options
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VoteOptions record);
}