package com.hqw.voteme.mapper;

import com.hqw.voteme.domain.VoteContent;

public interface VoteContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_content
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_content
     *
     * @mbggenerated
     */
    int insert(VoteContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_content
     *
     * @mbggenerated
     */
    int insertSelective(VoteContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_content
     *
     * @mbggenerated
     */
    VoteContent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VoteContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VoteContent record);
}