package com.hqw.voteme.domain;

import java.math.BigDecimal;
import java.util.Date;

public class UserProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.user_profile_id
     *
     * @mbggenerated
     */
    private Integer userProfileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.gender
     *
     * @mbggenerated
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.mobile_phone
     *
     * @mbggenerated
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.area
     *
     * @mbggenerated
     */
    private BigDecimal area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.village_id
     *
     * @mbggenerated
     */
    private Integer villageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.property_right_no
     *
     * @mbggenerated
     */
    private String propertyRightNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.user_profile_id
     *
     * @return the value of user_profile.user_profile_id
     *
     * @mbggenerated
     */
    public Integer getUserProfileId() {
        return userProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.user_profile_id
     *
     * @param userProfileId the value for user_profile.user_profile_id
     *
     * @mbggenerated
     */
    public void setUserProfileId(Integer userProfileId) {
        this.userProfileId = userProfileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.user_id
     *
     * @return the value of user_profile.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.user_id
     *
     * @param userId the value for user_profile.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.gender
     *
     * @return the value of user_profile.gender
     *
     * @mbggenerated
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.gender
     *
     * @param gender the value for user_profile.gender
     *
     * @mbggenerated
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.real_name
     *
     * @return the value of user_profile.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.real_name
     *
     * @param realName the value for user_profile.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.avatar
     *
     * @return the value of user_profile.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.avatar
     *
     * @param avatar the value for user_profile.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.mobile_phone
     *
     * @return the value of user_profile.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.mobile_phone
     *
     * @param mobilePhone the value for user_profile.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.id_card
     *
     * @return the value of user_profile.id_card
     *
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.id_card
     *
     * @param idCard the value for user_profile.id_card
     *
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.area
     *
     * @return the value of user_profile.area
     *
     * @mbggenerated
     */
    public BigDecimal getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.area
     *
     * @param area the value for user_profile.area
     *
     * @mbggenerated
     */
    public void setArea(BigDecimal area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.address
     *
     * @return the value of user_profile.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.address
     *
     * @param address the value for user_profile.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.village_id
     *
     * @return the value of user_profile.village_id
     *
     * @mbggenerated
     */
    public Integer getVillageId() {
        return villageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.village_id
     *
     * @param villageId the value for user_profile.village_id
     *
     * @mbggenerated
     */
    public void setVillageId(Integer villageId) {
        this.villageId = villageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.property_right_no
     *
     * @return the value of user_profile.property_right_no
     *
     * @mbggenerated
     */
    public String getPropertyRightNo() {
        return propertyRightNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.property_right_no
     *
     * @param propertyRightNo the value for user_profile.property_right_no
     *
     * @mbggenerated
     */
    public void setPropertyRightNo(String propertyRightNo) {
        this.propertyRightNo = propertyRightNo == null ? null : propertyRightNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.update_date
     *
     * @return the value of user_profile.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.update_date
     *
     * @param updateDate the value for user_profile.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}