package com.hqw.voteme.domain;

public class VillageManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_manager.village_manager_id
     *
     * @mbggenerated
     */
    private Integer villageManagerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_manager.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_manager.area_type
     *
     * @mbggenerated
     */
    private String areaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_manager.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_manager.village_manager_id
     *
     * @return the value of village_manager.village_manager_id
     *
     * @mbggenerated
     */
    public Integer getVillageManagerId() {
        return villageManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_manager.village_manager_id
     *
     * @param villageManagerId the value for village_manager.village_manager_id
     *
     * @mbggenerated
     */
    public void setVillageManagerId(Integer villageManagerId) {
        this.villageManagerId = villageManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_manager.user_id
     *
     * @return the value of village_manager.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_manager.user_id
     *
     * @param userId the value for village_manager.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_manager.area_type
     *
     * @return the value of village_manager.area_type
     *
     * @mbggenerated
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_manager.area_type
     *
     * @param areaType the value for village_manager.area_type
     *
     * @mbggenerated
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_manager.area_id
     *
     * @return the value of village_manager.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_manager.area_id
     *
     * @param areaId the value for village_manager.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }
}