package com.hqw.voteme.domain;

public class VillageInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_info.village_name
     *
     * @mbggenerated
     */
    private String villageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_info.village_code
     *
     * @mbggenerated
     */
    private String villageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_info.village_lng
     *
     * @mbggenerated
     */
    private String villageLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_info.vilage_lat
     *
     * @mbggenerated
     */
    private String vilageLat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column village_info.vilage_addr
     *
     * @mbggenerated
     */
    private String vilageAddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_info.id
     *
     * @return the value of village_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_info.id
     *
     * @param id the value for village_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_info.village_name
     *
     * @return the value of village_info.village_name
     *
     * @mbggenerated
     */
    public String getVillageName() {
        return villageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_info.village_name
     *
     * @param villageName the value for village_info.village_name
     *
     * @mbggenerated
     */
    public void setVillageName(String villageName) {
        this.villageName = villageName == null ? null : villageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_info.village_code
     *
     * @return the value of village_info.village_code
     *
     * @mbggenerated
     */
    public String getVillageCode() {
        return villageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_info.village_code
     *
     * @param villageCode the value for village_info.village_code
     *
     * @mbggenerated
     */
    public void setVillageCode(String villageCode) {
        this.villageCode = villageCode == null ? null : villageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_info.village_lng
     *
     * @return the value of village_info.village_lng
     *
     * @mbggenerated
     */
    public String getVillageLng() {
        return villageLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_info.village_lng
     *
     * @param villageLng the value for village_info.village_lng
     *
     * @mbggenerated
     */
    public void setVillageLng(String villageLng) {
        this.villageLng = villageLng == null ? null : villageLng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_info.vilage_lat
     *
     * @return the value of village_info.vilage_lat
     *
     * @mbggenerated
     */
    public String getVilageLat() {
        return vilageLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_info.vilage_lat
     *
     * @param vilageLat the value for village_info.vilage_lat
     *
     * @mbggenerated
     */
    public void setVilageLat(String vilageLat) {
        this.vilageLat = vilageLat == null ? null : vilageLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column village_info.vilage_addr
     *
     * @return the value of village_info.vilage_addr
     *
     * @mbggenerated
     */
    public String getVilageAddr() {
        return vilageAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column village_info.vilage_addr
     *
     * @param vilageAddr the value for village_info.vilage_addr
     *
     * @mbggenerated
     */
    public void setVilageAddr(String vilageAddr) {
        this.vilageAddr = vilageAddr == null ? null : vilageAddr.trim();
    }
}