package com.hqw.voteme.domain;

public class VoteOptions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_options.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_options.content_id
     *
     * @mbggenerated
     */
    private Integer contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_options.option
     *
     * @mbggenerated
     */
    private String option;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_options.option_id
     *
     * @mbggenerated
     */
    private String optionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_options.id
     *
     * @return the value of vote_options.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_options.id
     *
     * @param id the value for vote_options.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_options.content_id
     *
     * @return the value of vote_options.content_id
     *
     * @mbggenerated
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_options.content_id
     *
     * @param contentId the value for vote_options.content_id
     *
     * @mbggenerated
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_options.option
     *
     * @return the value of vote_options.option
     *
     * @mbggenerated
     */
    public String getOption() {
        return option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_options.option
     *
     * @param option the value for vote_options.option
     *
     * @mbggenerated
     */
    public void setOption(String option) {
        this.option = option == null ? null : option.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_options.option_id
     *
     * @return the value of vote_options.option_id
     *
     * @mbggenerated
     */
    public String getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_options.option_id
     *
     * @param optionId the value for vote_options.option_id
     *
     * @mbggenerated
     */
    public void setOptionId(String optionId) {
        this.optionId = optionId == null ? null : optionId.trim();
    }
}