package com.hqw.voteme.domain;

import java.util.Date;

public class VoteContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_content.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_content.vote_content
     *
     * @mbggenerated
     */
    private String voteContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_content.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_content.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_content.reserve
     *
     * @mbggenerated
     */
    private String reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_content.village_id
     *
     * @mbggenerated
     */
    private Integer villageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_content.id
     *
     * @return the value of vote_content.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_content.id
     *
     * @param id the value for vote_content.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_content.vote_content
     *
     * @return the value of vote_content.vote_content
     *
     * @mbggenerated
     */
    public String getVoteContent() {
        return voteContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_content.vote_content
     *
     * @param voteContent the value for vote_content.vote_content
     *
     * @mbggenerated
     */
    public void setVoteContent(String voteContent) {
        this.voteContent = voteContent == null ? null : voteContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_content.create_time
     *
     * @return the value of vote_content.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_content.create_time
     *
     * @param createTime the value for vote_content.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_content.end_time
     *
     * @return the value of vote_content.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_content.end_time
     *
     * @param endTime the value for vote_content.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_content.reserve
     *
     * @return the value of vote_content.reserve
     *
     * @mbggenerated
     */
    public String getReserve() {
        return reserve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_content.reserve
     *
     * @param reserve the value for vote_content.reserve
     *
     * @mbggenerated
     */
    public void setReserve(String reserve) {
        this.reserve = reserve == null ? null : reserve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_content.village_id
     *
     * @return the value of vote_content.village_id
     *
     * @mbggenerated
     */
    public Integer getVillageId() {
        return villageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_content.village_id
     *
     * @param villageId the value for vote_content.village_id
     *
     * @mbggenerated
     */
    public void setVillageId(Integer villageId) {
        this.villageId = villageId;
    }
}